name: golfinho
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.2
  google_sign_in: ^5.0.7
  http: ^0.13.6
  flutter_signin_button: ^2.0.0
  dart_ping: ^8.0.1
  internet_speed_test: ^1.5.0
  network_info_plus: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_internet_speed_test: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
